databases:
  - name: budgetlydb
    databaseName: budgetlydb
    user: budgetlydb_user

services:
  - type: web
    name: budgetly-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetlydb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false